# Site settings
title: Alexey Maslennikov
subtitle: Thoughts on becoming a professional

email: alexey@maslennikov.me
description: > # this means to ignore newlines until "baseurl:"
  A blog of Alexey Maslennikov: notes on lifestyle, business,
  and self-improvement.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.maslennikov.me" # the base hostname & protocol for your site
permalink: /posts/:title

twitter_username: _maslennikov
github_username:  maslennikov

# Build settings
markdown: kramdown
